### ISSUE TITLE
训练完成后导入好的模型，每次计算后fc都是一个固定的值。

### ISSUE THREAD

**Issue by dzyjjpy** [stephen-v/tensorflow_alexnet_classify#3]
如题，使用saver.restore方法导入训练好的模型，每次调用函数test_image后，输出的全连接层fc8得到的特征向量，都是一个固定的值。替换一张输入图片，仍然是相同的值，麻烦作者再坐下检查。

**Comment by qq547276542** [comment]
> 如题，使用saver.restore方法导入训练好的模型，每次调用函数test_image后，输出的全连接层fc8得到的特征向量，都是一个固定的值。替换一张输入图片，仍然是相同的值，麻烦作者再坐下检查。

您好，请问您的问题解决了吗？我遇到了类似的问题

**Comment by qq547276542** [comment]
> 如题，使用saver.restore方法导入训练好的模型，每次调用函数test_image后，输出的全连接层fc8得到的特征向量，都是一个固定的值。替换一张输入图片，仍然是相同的值，麻烦作者再坐下检查。

找到原因了。  训练的代码里，所有图像的像素都减去了VGG_MEAN，但是在预测时作者忘记加入同样的处理了。
麻烦作者更正一下， 此外感谢作者的开源

**Comment by dzyjjpy** [comment]
收到，Thanks
